name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: java -version && mvn --version
    - run: mvn --activate-profiles dist --no-transfer-progress package
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          bootstrap/target/BungeeCord.jar
          module/cmd-alert/target/cmd_alert.jar
          module/cmd-find/target/cmd_find.jar
          module/cmd-list/target/cmd_list.jar
          module/cmd-send/target/cmd_send.jar
          module/cmd-server/target/cmd_server.jar
          module/reconnect-yaml/target/reconnect_yaml.jar
        
